name: fetch-yf

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - run: pip install -r requirements.txt
      - run: python test.py
      - uses: actions/upload-artifact@v4
        with:
          name: yf
          path: yf.csv