name: Fetch Yahoo Finance Data

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run python script
        run: python test.py

      - name: Upload yfinance data artifact
        uses: actions/upload-artifact@v4
        with:
          name: yfinance-data
          path: yf.csv
