name: Data Pipeline
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Run script
      run: python test.py
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: yf-data
        path: yf.csv